 <option value="2">Advertising/Media</option>
 <option value="3">Agriculture/Aquaculture/Forestry</option>
 <option value="5">Airline Operation/Airport Management</option>
 <option value="4">Architecture</option>
 <option value="1">Art/Design/Creative Multimedia</option>
 <option value="6">Biology</option>
 <option value="55">BioTechnology</option>
 <option value="36">Business Studies/Administration/Management</option>
 <option value="7">Chemistry</option>
 <option value="54">Commerce</option>
 <option value="8">Computer Science/Information Technology</option>
 <option value="9">Dentistry</option>
 <option value="15">Economics</option>
 <option value="17">Education/Teaching/Training</option><option value="12">Engineering (Aviation/Aeronautics/Astronautics)</option><option value="101">Engineering (Bioengineering/Biomedical)</option><option value="13">Engineering (Chemical)</option><option value="14">Engineering (Civil)</option><option value="16">Engineering (Computer/Telecommunication)</option><option value="18">Engineering (Electrical/Electronic)</option><option value="24">Engineering (Environmental/Health/Safety)</option><option value="19">Engineering (Industrial)</option><option value="23">Engineering (Marine)</option><option value="21">Engineering (Material Science)</option><option value="20">Engineering (Mechanical)</option><option value="102">Engineering (Mechatronic/Electromechanical)</option><option value="22">Engineering (Metal Fabrication/Tool &amp; Die/Welding)</option><option value="103">Engineering (Mining/Mineral)</option><option value="25">Engineering (Others)</option><option value="26">Engineering (Petroleum/Oil/Gas)</option><option value="28">Finance/Accountancy/Banking</option><option value="27">Food &amp; Beverage Services Management</option><option value="104">Food Technology/Nutrition/Dietetics</option><option value="11">Geographical Science</option><option value="105">Geology/Geophysics</option><option value="106">History</option><option value="29">Hospitality/Tourism/Hotel Management</option><option value="30">Human Resource Management</option><option value="32">Humanities/Liberal Arts</option><option value="10">Journalism</option><option value="31">Law</option><option value="33">Library Management</option><option value="34">Linguistics/Languages</option><option value="35">Logistic/Transportation</option><option value="41">Maritime Studies</option><option value="49">Marketing</option><option value="37">Mass Communications</option><option value="38">Mathematics</option><option value="40">Medical Science</option><option value="39">Medicine</option><option value="42">Music/Performing Arts Studies</option><option value="43">Nursing</option><option value="107">Optometry</option><option value="47">Personal Services</option><option value="45">Pharmacy/Pharmacology</option><option value="108">Philosophy</option><option value="109">Physical Therapy/Physiotherapy</option><option value="46">Physics</option><option value="110">Political Science</option><option value="111">Property Development/Real Estate Management</option><option value="48">Protective Services &amp; Management</option><option value="112">Psychology</option><option value="100">Quantity Survey</option><option value="50">Science &amp; Technology</option><option value="51">Secretarial</option><option value="113">Social Science/Sociology</option><option value="114">Sports Science &amp; Management</option><option value="52">Textile/Fashion Design</option><option value="115">Urban Studies/Town Planning</option><option value="53">Veterinary</option><option value="44">Others</option>
